version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@1.0.0

workflows:
  - build_and_deploy:
    jops:
      - build:
        filters:
          branches:
            only:
              - main
      - deploy:
        requires:
          - build

jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout

      - run:
          name: DevDepend Install
          command: |
            npm install


      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run api:install


      - run:
          name: Front-End Build
          command: |
            npm run frontend:build

      - run:
          name: Back-End Build
          command: |
            npm run api:build


  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - aws-cli/setup
      - eb/setup
      - checkout

      - run:
          name: Back-End Deploy
          command: |
            npm run api:deploy
      - run:
          name: Front-End Deploy
          command: |
            npm run frontend:deploy